"""
BlenderToRCP Add-on

A Blender extension to export scenes to Reality Composer Pro format.
"""

_needs_reload = "bpy" in locals()

try:
    import bpy as _bpy  # type: ignore
    # Sanity-check: some environments may have a stub `bpy` module installed.
    from bpy.props import StringProperty as _StringProperty  # noqa: F401
except Exception:  # Allows importing non-Blender utilities from this package.
    bpy = None
else:
    bpy = _bpy

if bpy is not None:
    from . import prefs as prefs_module
    from . import ui as ui_module
    from . import ops as ops_module
else:
    prefs_module = None
    ui_module = None
    ops_module = None

if bpy is not None and _needs_reload:
    import importlib
    prefs_module = importlib.reload(prefs_module)
    ui_module = importlib.reload(ui_module)
    ops_module = importlib.reload(ops_module)
    print("BlenderToRCP Add-on Reloaded")


bl_info = {
    "name": "BlenderToRCP",
    "author": "Your Name",
    "version": (1, 0, 0),
    "blender": (5, 0, 0),
    "location": "View3D > UI",
    "description": "Export Blender scenes to Reality Composer Pro format",
    "warning": "Requires OpenUSD Python bindings (pxr) for material rewriting",
    "doc_url": "",
    "category": "Import-Export",
}


def register():
    """Register the add-on's classes and properties."""
    if bpy is None:
        raise RuntimeError("BlenderToRCP must be run inside Blender (bpy not available).")

    prefs_module.register()
    ops_module.register()
    ui_module.register()

    # The MaterialX nodedef manifest is a built artifact (generated by a repo script).
    # We intentionally do not rebuild it at runtime inside Blender.
    try:
        from .manifest.materialx_nodes import get_manifest_path, load_manifest

        manifest_path = get_manifest_path()
        if not manifest_path.exists():
            print(
                "Warning: MaterialX manifest missing. "
                "Run `python3 scripts/build_materialx_manifest.py` to generate it."
            )
        else:
            load_manifest()
    except Exception as e:
        print(f"Warning: Could not load MaterialX manifest: {e}")


def unregister():
    """Unregister the add-on's classes and properties."""
    if bpy is None:
        return

    ui_module.unregister()
    ops_module.unregister()
    prefs_module.unregister()


if __name__ == "__main__":
    register()
